env: "dev"
storage_path:
  POSTGRES_PASSWORD: "123456"
  POSTGRES_HOST: "localhost"
  POSTGRES_USER: "postgre"
  POSTGRES_DB: "postgre"
  POSTGRES_PORT: "5432"
grpc:
  port: 44045
  timeout: 1h

tarantool:
  HOST: "127.0.0.1:3301"
  USER: "admin"
  PASS: "pass"

dev_db: "./dev.db"
secret: "dasdasdd"